# TMBD Data API
----

In [21]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import os
import locale # to format currency as USD
locale.setlocale( locale.LC_ALL, '' )

# Import API key
from api_keys import api_key

# Output File (CSV)
output_data_file = "tmbddata.csv"

## Generate Movies Database from TMBD API

r = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=' +  api_key)
highest_revenue_ever = r.json()
r.json()

{'page': 1,
 'total_results': 10000,
 'total_pages': 500,
 'results': [{'popularity': 496.072,
   'vote_count': 1738,
   'video': False,
   'poster_path': '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
   'id': 419704,
   'adult': False,
   'backdrop_path': '/p3TCqUDoVsrIm8fHK9KOTfWnDjZ.jpg',
   'original_language': 'en',
   'original_title': 'Ad Astra',
   'genre_ids': [12, 18, 9648, 878, 53],
   'title': 'Ad Astra',
   'vote_average': 6,
   'overview': 'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
   'release_date': '2019-09-17'},
  {'popularity': 292.11,
   'vote_count': 2153,
   'video': False,
   'poster_path': '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
   'id': 181812,
   'adult': False,
   'backdrop_path': '/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg',
   'original_language': 'en',
   'original_title': 'Star Wars: The Rise of Skywalker',
   'genre_ids': [28, 12, 878],
   'title': 'Star Wars: The Rise of Skywalker',
   'vote_average': 6.6,
   'overview': 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
   'release_date': '2019-12-18'},
  {'popularity': 200.703,
   'vote_count': 1286,
   'video': False,
   'poster_path': '/vloNTScJ3w7jwNwtNGoG8DbTThv.jpg',
   'id': 420809,
   'adult': False,
   'backdrop_path': '/skvI4rYFrKXS73BJxWGH54Omlvv.jpg',
   'original_language': 'en',
   'original_title': 'Maleficent: Mistress of Evil',
   'genre_ids': [12, 14, 10751],
   'title': 'Maleficent: Mistress of Evil',
   'vote_average': 7.2,
   'overview': 'Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions by impending nuptials, unexpected allies, and dark new forces at play.',
   'release_date': '2019-10-16'},
  {'popularity': 236.952,
   'vote_count': 923,
   'video': False,
   'poster_path': '/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg',
   'id': 512200,
   'adult': False,
   'backdrop_path': '/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg',
   'original_language': 'en',
   'original_title': 'Jumanji: The Next Level',
   'genre_ids': [28, 12, 35, 14],
   'title': 'Jumanji: The Next Level',
   'vote_average': 6.7,
   'overview': 'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
   'release_date': '2019-12-04'},
  {'popularity': 224.98,
   'vote_count': 7539,
   'video': False,
   'poster_path': '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
   'id': 475557,
   'adult': False,
   'backdrop_path': '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
   'original_language': 'en',
   'original_title': 'Joker',
   'genre_ids': [80, 18, 53],
   'title': 'Joker',
   'vote_average': 8.3,
   'overview': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
   'release_date': '2019-10-02'},
  {'popularity': 165.855,
   'vote_count': 119,
   'video': False,
   'poster_path': '/yJdeWaVXa2se9agI6B4mQunVYkB.jpg',
   'id': 449924,
   'adult': False,
   'backdrop_path': '/ekP6EVxL81lZ4ivcqPsoZ72rY0h.jpg',
   'original_language': 'cn',
   'original_title': '葉問4',
   'genre_ids': [28, 18, 36],
   'title': 'Ip Man 4: The Finale',
   'vote_average': 5.7,
   'overview': 'Following the death of his wife, Ip Man travels to San Francisco to ease tensions between the local kung fu masters and his star student, Bruce Lee, while searching for a better future for his son.',
   'release_date': '2019-12-20'},
  {'popularity': 185.285,
   'vote_count': 1623,
   'video': False,
   'poster_path': '/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg',
   'id': 330457,
   'adult': False,
   'backdrop_path': '/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg',
   'original_language': 'en',
   'original_title': 'Frozen II',
   'genre_ids': [12, 16, 10402, 10751],
   'title': 'Frozen II',
   'vote_average': 7,
   'overview': 'Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.',
   'release_date': '2019-11-20'},
  {'popularity': 124.67,
   'vote_count': 1059,
   'video': False,
   'poster_path': '/uTALxjQU8e1lhmNjP9nnJ3t2pRU.jpg',
   'id': 453405,
   'adult': False,
   'backdrop_path': '/sfW7GcOuwZFuCxVoU5ULlkiDJ7Q.jpg',
   'original_language': 'en',
   'original_title': 'Gemini Man',
   'genre_ids': [28, 53],
   'title': 'Gemini Man',
   'vote_average': 5.8,
   'overview': 'Ageing assassin, Henry Brogen tries to get out of the business but finds himself in the ultimate battle—fighting his own clone who is 25 years younger than him, and at the peak of his abilities.',
   'release_date': '2019-10-02'},
  {'popularity': 128.423,
   'vote_count': 288,
   'video': False,
   'poster_path': '/u50NAzMDBxTBP0CwmuUmBUkxW05.jpg',
   'id': 593402,
   'adult': False,
   'backdrop_path': '/5QuRbno7OLgXi9bz5YXKrtn3vFH.jpg',
   'original_language': 'es',
   'original_title': 'Tolo Tolo',
   'genre_ids': [35],
   'title': 'Tolo Tolo',
   'vote_average': 6.4,
   'overview': 'Checco is a young Apulian entrepreneur dreamer who has opened a sushi restaurant in his Apulia. However, after one month, the restaurant went bankrupt and he chose to emigrate to Africa to escape from debt. Here he adapts to being a waiter in a resort in Kenya, but at the outbreak of a civil war he decides to embark on a stowaway trip on a boat for migrants to Europe and chooses to do it with his African friends. However, he would not like to return to Italy, but rather to go to Liechtenstein where banking secrecy is in force and there is a lower tax burden than in Italy.',
   'release_date': '2020-01-01'},
  {'popularity': 121.234,
   'vote_count': 42,
   'video': False,
   'poster_path': '/eU0orGizEpOli4wtN8HtfOOJDlA.jpg',
   'id': 516700,
   'adult': False,
   'backdrop_path': '/mlaX4c2M6usnhXHG5sYJcKVXflA.jpg',
   'original_language': 'id',
   'original_title': 'Gundala',
   'genre_ids': [28, 80, 18],
   'title': 'Gundala',
   'vote_average': 5.4,
   'overview': 'Sancaka has lived on the streets since his parents left him. Living a hard life, Sancaka survives by thinking about his own safety. When the condition of the city gets worse and injustice rages throughout the country, Sancaka must decide whether he continues to live to look after himself or rise to become their oppressed hero.',
   'release_date': '2019-08-29'},
  {'popularity': 113.627,
   'vote_count': 2223,
   'video': False,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'id': 496243,
   'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'original_language': 'ko',
   'original_title': '기생충',
   'genre_ids': [35, 18, 53],
   'title': 'Parasite',
   'vote_average': 8.6,
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'release_date': '2019-05-30'},
  {'popularity': 102.42,
   'vote_count': 3794,
   'video': False,
   'poster_path': '/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',
   'id': 466272,
   'adult': False,
   'backdrop_path': '/yB2hTgz9CTVYjlMWPSl3LPx5nWj.jpg',
   'original_language': 'en',
   'original_title': 'Once Upon a Time… in Hollywood',
   'genre_ids': [35, 18, 53],
   'title': 'Once Upon a Time… in Hollywood',
   'vote_average': 7.5,
   'overview': 'Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…',
   'release_date': '2019-07-25'},
  {'popularity': 91.701,
   'vote_count': 1300,
   'video': False,
   'poster_path': '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
   'id': 546554,
   'adult': False,
   'backdrop_path': '/cjTQSwcsfVdirSFSHNBXRGkxmWa.jpg',
   'original_language': 'en',
   'original_title': 'Knives Out',
   'genre_ids': [35, 80, 18, 9648, 53],
   'title': 'Knives Out',
   'vote_average': 7.8,
   'overview': "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
   'release_date': '2019-11-27'},
  {'popularity': 80.735,
   'vote_count': 1134,
   'video': False,
   'poster_path': '/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg',
   'id': 509967,
   'adult': False,
   'backdrop_path': '/eFw5YSorHidsajLTayo1noueIxI.jpg',
   'original_language': 'en',
   'original_title': '6 Underground',
   'genre_ids': [28, 35, 53],
   'title': '6 Underground',
   'vote_average': 6.2,
   'overview': 'After faking his death, a tech billionaire recruits a team of international operatives for a bold and bloody mission to take down a brutal dictator.',
   'release_date': '2019-12-13'},
  {'popularity': 73.294,
   'vote_count': 76,
   'video': False,
   'poster_path': '/MBiKqTsouYqAACLYNDadsjhhC0.jpg',
   'id': 486589,
   'adult': False,
   'backdrop_path': '/bga3i5jcejBekr2FCGJga1fYCh.jpg',
   'original_language': 'en',
   'original_title': 'Red Shoes and the Seven Dwarfs',
   'genre_ids': [16, 10749],
   'title': 'Red Shoes and the Seven Dwarfs',
   'vote_average': 6.6,
   'overview': 'Princes who have been turned into Dwarfs seek the red shoes of a lady in order to break the spell, although it will not be easy.',
   'release_date': '2019-07-25'},
  {'popularity': 72.1,
   'vote_count': 970,
   'video': False,
   'poster_path': '/dtRbVsUb5O12WWO54SRpiMtHKC0.jpg',
   'id': 338967,
   'adult': False,
   'backdrop_path': '/3ghImmHdp4RnC3UkL6hpLayclnb.jpg',
   'original_language': 'en',
   'original_title': 'Zombieland: Double Tap',
   'genre_ids': [28, 35, 27],
   'title': 'Zombieland: Double Tap',
   'vote_average': 7,
   'overview': 'Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.',
   'release_date': '2019-10-09'},
  {'popularity': 84.8,
   'vote_count': 811,
   'video': False,
   'poster_path': '/6ApDtO7xaWAfPqfi2IARXIzj8QS.jpg',
   'id': 359724,
   'adult': False,
   'backdrop_path': '/mn9k8zapebAbCqsiKf24juhXjjx.jpg',
   'original_language': 'en',
   'original_title': 'Ford v Ferrari',
   'genre_ids': [28, 18, 36],
   'title': 'Ford v Ferrari',
   'vote_average': 7.8,
   'overview': 'American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.',
   'release_date': '2019-11-13'},
  {'popularity': 54.052,
   'vote_count': 9611,
   'video': False,
   'poster_path': '/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg',
   'id': 181808,
   'adult': False,
   'backdrop_path': '/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg',
   'original_language': 'en',
   'original_title': 'Star Wars: The Last Jedi',
   'genre_ids': [28, 12, 14, 878],
   'title': 'Star Wars: The Last Jedi',
   'vote_average': 7,
   'overview': 'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.',
   'release_date': '2017-12-13'},
  {'popularity': 78.062,
   'vote_count': 384,
   'video': False,
   'poster_path': '/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg',
   'id': 503919,
   'adult': False,
   'backdrop_path': '/qlYhhBUseMUawwbvHCdPLXvBELv.jpg',
   'original_language': 'en',
   'original_title': 'The Lighthouse',
   'genre_ids': [18, 14, 27, 9648],
   'title': 'The Lighthouse',
   'vote_average': 7.9,
   'overview': 'Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.',
   'release_date': '2019-10-18'},
  {'popularity': 73.727,
   'vote_count': 978,
   'video': False,
   'poster_path': '/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg',
   'id': 423204,
   'adult': False,
   'backdrop_path': '/k2WyDw2NTUIWnuEs5gT7wgrCQg6.jpg',
   'original_language': 'en',
   'original_title': 'Angel Has Fallen',
   'genre_ids': [28, 53],
   'title': 'Angel Has Fallen',
   'vote_average': 5.9,
   'overview': 'After a treacherous attack, Secret Service agent Mike Banning is charged with attempting to assassinate President Trumbull. Chased by his own colleagues and the FBI, Banning begins a race against the clock to clear his name.',
   'release_date': '2019-08-21'}]}

In [ ]:
columns = ['film', release_date', vote_average, popularity]

In [22]:
#Create dataframe from JSON

columns = ['film', 'revenue', 'budget', 'release_date']
df = pd.DataFrame(columns=columns)
for film in highest_revenue_films_ever:
    film_revenue = requests.get('https://api.themoviedb.org/3/movie/'+ str(film['id']) +'?api_key='+ api_key+'&language=en-US')
    film_revenue = film_revenue.json()
    df.loc[len(df)]=[film['title'],film_revenue['revenue'], (film_revenue['budget'] * -1), film_revenue['release_date']]

In [23]:
df.head()

                            film       revenue        budget release_date
0       Arrietty (UK Voice Cast)  146000000000  -23000000000   2011-07-29
1  The Lord of the Rings Trilogy    2910000000    -281000000   2003-12-13
2              Avengers: Endgame    2797800564    -356000000   2019-04-24
3                         Avatar    2787965087    -237000000   2009-12-10
4             Spider-Man trilogy    2515648827          -589   2002-05-03

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [24]:
#create CSV file of raw data from OpenWeather API and store in Results Directory

In [25]:
#Create directory to store results
script_dir = os.path.dirname("")
results_dir = os.path.join(script_dir, 'Results/')
if not os.path.isdir(results_dir):
    os.makedirs(results_dir)
df.to_csv(results_dir + output_data_file)